version: '3.6'
services:
  nginx:
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
  db:
    image: linuxserver/mariadb:${MYSQL_VERSION:-10.11.10}
    hostname: db
    container_name: db
    restart: unless-stopped
    ports:
      - "${MYSQL_LISTEN_ADDR}:${MYSQL_LISTEN_PORT}:3306"
    expose:
      - ${MYSQL_LISTEN_PORT}
    volumes:
      - ./db/config:/config
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  migration:
    image: kcapp/api:$KCAPP_API_VERSION
    hostname: migration
    container_name: migration
    command: [ "./wait-for-it.sh", "db:3306", "--", "./run_migrations.sh" ]
    depends_on:
      - db
    environment:
      DB_CONNECTION: "${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(db:3306)/${MYSQL_DATABASE}?parseTime=true"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  api:
    image: kcapp/api:$KCAPP_API_VERSION
    hostname: api
    container_name: api
    restart: unless-stopped
    ports:
      - "${API_LISTEN_ADDR}:${API_LISTEN_PORT}:8001"
    expose:
      - ${API_LISTEN_PORT}
    depends_on:
      - migration
      - db
    command: [ "./wait-for-it.sh", "db:3306", "--", "/go/bin/api" ]
#   command: [ "./wait-for-it.sh", "db:3306", "--", "/go/bin/api statistics recalculate x01 --dry-run=false" ]
  
  frontend:
    image: kcapp/frontend:$KCAPP_FRONTEND_VERSION
    hostname: frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "${KCAPP_FRONTEND_LISTEN_ADDR}:${KCAPP_FRONTEND_LISTEN_PORT}:3000"
    expose:
      - ${KCAPP_FRONTEND_LISTEN_PORT}
    depends_on:
      - api
    environment:
      - DEBUG=kcapp*
      - KCAPP_API
      - DISK_CACHE
      - KCAPP_API_PATH
